### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{ "name": "Ethan Hunt", "email": "ethan@example.com", "address": "202 Birch Ln" }
###
POST http://localhost:8080/carts/1
Content-Type: application/json

{
  "id": 2
}